### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by philtoday** [britco/gulp-coffeedoc#1]
This package is not published on npm. Would you mind to publish it for easy installation through npm :) ?

**Comment by youurayy** [comment]
Yes please, we need it too!

**Comment by pdufour** [comment]
Published! https://www.npmjs.com/package/gulp-coffeedoc @philtoday @youurayy

**Comment by youurayy** [comment]
thanks! :)

**Comment by mojoio** [comment]
Wonderful indeed! :)
